name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      javascript: ${{ steps.changes.outputs.javascript }}
      python: ${{ steps.changes.outputs.python }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          javascript:
            - 'sdk/javascript/**'
          python:
            - 'sdk/python/**'

  test-javascript:
    needs: detect-changes
    if: needs.detect-changes.outputs.javascript == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      run: cd sdk/javascript && npm install
    - name: Run tests
      run: cd sdk/javascript && npm test
    - name: Run lint
      run: cd sdk/javascript && npm run lint

  test-python:
    needs: detect-changes
    if: needs.detect-changes.outputs.python == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: cd sdk/python && pip install -e .
    - name: Run tests
      run: cd sdk/python && python -m pytest test_logger.py -v
